services:
  node:
    container_name: burunzhuy_node
    build:
      context: .
      dockerfile: dockerfiles/node/Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:18
    container_name: burunzhuy_pgsql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'

  pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: burunzhuy_pgadmin
    ports:
      - "5434:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
      PMA_HOST: db

  redis:
    build: ./dockerfiles/redis
    volumes:
      - .:/usr/src/app
      - ./dockerfiles/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: burunzhuy_redis
    ports:
      - "6379:6379"